[package]
name = "usbsorter"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = { version = "0.5.2", package = "libadwaita", features = ["v1_3"] }
fatfs = "0.3.6"
fscommon = "0.1.1"
gtk = { version = "0.7.1", package = "gtk4", features = ["v4_10"] }
sudo = "0.6.0"

utils = {path="./utils"}
